# Default configuration using H2 in-memory database
spring:
  datasource:
    url: jdbc:h2:mem:eaglebankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: 8080
  main.show-banner: false

management:
  endpoints:
    web:
      exposure:
        include: [health, metrics, prometheus]
